# Generated by Django 5.2.4 on 2025-08-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_email_from_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Company'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
