# Generated by Django 5.2.4 on 2025-09-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mentor_company_mentor_linkedin_url_mentor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentor_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
